"""empty message

Revision ID: e6045425d154
Revises: e4affe8650c6
Create Date: 2021-08-04 13:57:35.130081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6045425d154'
down_revision = 'e4affe8650c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userWallets', sa.Column('buyingPower', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('userWallets', 'buyingPower')
    # ### end Alembic commands ###
