"""empty message

Revision ID: 394909db29b0
Revises: ffdc0a98111c
Create Date: 2021-07-29 02:32:47.607644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '394909db29b0'
down_revision = 'ffdc0a98111c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('farms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('averageYield', sa.Float(), nullable=True),
    sa.Column('averageSharePrice', sa.Float(), nullable=True),
    sa.Column('averageRating', sa.Numeric(precision=2, scale=1), nullable=True),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('location')
    )
    op.create_table('userWallets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('farmWallets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farmId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['farmId'], ['farms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions',
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('farmId', sa.Integer(), nullable=False),
    sa.Column('usdAmount', sa.Float(), nullable=False),
    sa.Column('shares', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['farmId'], ['farms.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('userId', 'farmId')
    )
    op.add_column('users', sa.Column('image_url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'image_url')
    op.drop_table('transactions')
    op.drop_table('farmWallets')
    op.drop_table('userWallets')
    op.drop_table('farms')
    # ### end Alembic commands ###
