"""empty message

Revision ID: e4affe8650c6
Revises: 394909db29b0
Create Date: 2021-07-29 18:06:56.473048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4affe8650c6'
down_revision = '394909db29b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saved_farms',
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('farmId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['farmId'], ['farms.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('userId', 'farmId')
    )
    op.add_column('farmWallets', sa.Column('shares', sa.Integer(), nullable=True))
    op.add_column('farms', sa.Column('about', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('farms', 'about')
    op.drop_column('farmWallets', 'shares')
    op.drop_table('saved_farms')
    # ### end Alembic commands ###
