"""empty message

Revision ID: d9557b2c45b6
Revises: ac1ea8462944
Create Date: 2021-08-07 18:24:29.275347

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd9557b2c45b6'
down_revision = 'ac1ea8462944'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'usdAmount',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('transactions', 'shares',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'shares',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('transactions', 'usdAmount',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    # ### end Alembic commands ###
